nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-angular.cjs
    spec: "https://github.com/bgotink/yarn-plugin-angular/raw/latest/bin/%40yarnpkg/plugin-angular.js"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
